name: Build and upload artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    - name: 'Build and package'
      run: |
        go install github.com/fyne-io/fyne-cross@latest
        fyne-cross windows
        fyne-cross linux

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        # Artifact name
        name: pdfmerge
        # A file, directory or wildcard pattern that describes what to upload
        path: "fyne-cross/dist" 
